[package]
name = "AptosRoulette"
version = "1.0.0"
authors = []

[addresses]
casino = "_"
roulette_game = "_"

[dev-addresses]
casino = "0xCC"
roulette_game = "0x1234"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-framework.git"
rev = "mainnet"
subdir = "aptos-framework"

[dependencies.ChainCasino]
git = "https://github.com/PersonaNormale/ChainCasino.git"
rev = "feature/contracts-refining"

[dev-dependencies]
